name: Build Firmware

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Board target (e.g. EMAX_TINYHAWKF4SX1280)'
        required: true
      revision:
        description: 'Firmware revision (commit SHA or tag, leave blank for latest)'
        required: false
      config-repo:
        description: 'URL of the config repository'
        required: false
      config-branch:
        description: 'Branch of the config repository'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Betaflight source
        uses: actions/checkout@v4

      - name: Set revision
        id: vars
        run: |
          echo "REVISION=${{ github.event.inputs.revision || 'master' }}" >> $GITHUB_ENV
          echo "CONFIG_REPO=${{ github.event.inputs['config-repo'] || 'betaflight/config' }}" >> $GITHUB_ENV
          echo "CONFIG_BRANCH=${{ github.event.inputs['config-branch'] || 'master' }}" >> $GITHUB_ENV

      - name: Checkout config repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CONFIG_REPO }}
          ref: ${{ env.CONFIG_BRANCH }}
          path: config

      - name: Install dependencies and correct ARM toolchain
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip scons
          pip3 install --upgrade pip
          make arm_sdk_install

      - name: Hydrate config directory
        run: make configs CONFIG_REPO=./config

      - name: Build firmware
        run: |
          echo "Building target: ${{ github.event.inputs.target }}"
          make ${{ github.event.inputs.target }} CONFIG_REPO=./config

      - name: List build directory
        run: ls -R obj/${{ github.event.inputs.target }} || echo "Build folder not found"

      - name: Upload firmware artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ github.event.inputs.target }}
          path: obj/${{ github.event.inputs.target }}/*.hex
